apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-success-rate
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
  - name: service-name
    value: istio-rollout-canary.rollouts-demo-istio.svc.cluster.local
  # - name: namespace
  #   value: rollouts-demo-istio
  metrics:
  - name: success-rate
    initialDelay: 60s
    interval: 20s
    successCondition: result[0] > 0.90
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: >+
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service-name}}",
            response_code!~"5.*"}[40s])
          )
          /
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service-name}}"}[40s])
          )
