apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio.dev.tiktak.egged.co.il	
  http:
  - name: primary
  - match:
    - uri:
        exact: /istio-rollout-app
    route:
    - destination:
        host: istio-rollout-stable
      weight: 100
    - destination:
        host: istio-rollout-canary
      weight: 0
